Repository MarcoOquendoC/CatalogOfMyThings-RubyCapstone, pull requests merged in 2023-01, with the labels that each got.

#34 Implement startup actions
  .rubocop.yml
  app.rb
  app_modules/book/add_book.rb
  app_modules/book/list_books.rb
  app_modules/book/list_labels.rb
  app_modules/first_menu.rb
  app_modules/game/add_game.rb
  app_modules/game/list_authors.rb
  app_modules/game/list_games.rb
  app_modules/music/add_music_album.rb
  app_modules/music/list_genres.rb
  app_modules/music/list_music_albums.rb
  app_modules/process_option.rb
Labels: UI

#35 Create Game and Author class
  app.rb
  app_modules/first_menu.rb
  game/author.rb
  game/game.rb
  src/item.rb
Labels: Class, OOP

#40 Add specs for Book and Label classes
  book/book.rb
  spec/book_spec.rb
  spec/label_spec.rb
  spec/spec_helper.rb
Labels: Rspec, Unit test

#42 Add options for author and game by preserving data
  app.rb
  app_modules/game/add_game.rb
  app_modules/game/list_authors.rb
  app_modules/game/list_games.rb
  data/authors.json
  data/games.json
  game/game.rb
  game/preserve_data.rb
  spec/game/author_spec.rb
  spec/game/game_spec.rb
Labels: UI, JSON

#43 Implement book and label creation
  app.rb
  app_modules/book/add_book.rb
  app_modules/book/list_books.rb
  app_modules/book/list_labels.rb
Labels: UI

#44 Add Analogical schema.sql for games and author tables
  app_modules/game/list_games.rb
  game/preserve_data.rb
  sql/schema.sql
Labels: SQL, PLpgSQL

#46 Feature/options music album genre
  .rubocop.yml
  app.rb
  app_modules/first_menu.rb
  app_modules/goodbye.rb
  app_modules/greetings.rb
  app_modules/music/add_music_album.rb
  app_modules/music/list_genres.rb
  app_modules/music/list_music_albums.rb
  music/music_album.rb
  spec/music/genre_spec.rb
  spec/music/music_album_spec.rb
Labels: UI

#50 Feature/preserve musicalbums genres
  app.rb
  app_modules/music/add_music_album.rb
  app_modules/music/list_music_albums.rb
  data/albums.json
  data/genres.json
  music/genre.rb
  music/load.rb
  music/music_album.rb
  music/preserve.rb
  src/item.rb
Labels: JSON

#52 Update README md
  .rubocop.yml
  app_modules/book/add_book.rb
  app_modules/game/add_game.rb
  app_modules/music/list_genres.rb
  book/persist_books.rb
  data/albums.json
  data/authors.json
  data/books.json
  data/games.json
  data/genres.json
  data/labels.json
  music/load.rb
Labels: documentation

#54 Feature/cool coments
  app_modules/book/add_book.rb
  app_modules/book/list_books.rb
  app_modules/book/list_labels.rb
  app_modules/game/add_game.rb
  app_modules/game/list_authors.rb
  app_modules/game/list_games.rb
  app_modules/music/add_music_album.rb
  app_modules/music/list_genres.rb
  app_modules/music/list_music_albums.rb
Labels: enhancement

#59 Add Diagram
  README.md
Labels: documentation, Readme
